### ISSUE TITLE
Proxy setup

### ISSUE THREAD

**Issue by EdgeBow** [xtekky/gpt4free#1078]
Ask under which file the proxy is set?

**Comment by hlohaus** [comment]
Try:
https://github.com/xtekky/gpt4free#proxy-support
```
response = await g4f.ChatCompletion.create_async(
    model=g4f.models.default,
    provider=g4f.Provider.Opchatgpts,
    messages=[{"role": "user", "content": "Hello"}],
    proxy="http://host:port",
    # or socks5://user:pass@host:port
)
```

**Comment by EdgeBow** [comment]
> Try: https://github.com/xtekky/gpt4free#proxy-support
> 
> ```
> response = await g4f.ChatCompletion.create_async(
>     model=g4f.models.default,
>     provider=g4f.Provider.Opchatgpts,
>     messages=[{"role": "user", "content": "Hello"}],
>     proxy="http://host:port",
>     # or socks5://user:pass@host:port
> )
> ```
Please ask under which file you need to add these contents

**Comment by koutkout** [comment]
since the update of 0.1.6.8 socks5 proxies are not working at all. . .can you check please?
can you also please highlight which one are working with socks5 and which need an http proxy?
if you can help us find a software to make a bridge http proxy to a socks5 proxy then that would also be appreciated, in case solving the issue of socks5 proxy is not easy.
