### ISSUE TITLE
I reversed a site called app.suno.ai, basically it's music gen AI should I add it here ?

### ISSUE THREAD

**Issue by Meshwa428** [xtekky/gpt4free#1555]
I reverse engineered the music gen feature of (https://app.suno.ai/create), this allows us to create songs using ai.

Write your prompt/description of your song and viola you will have 2 audio files downloaded to your device.

I want to ask @hlohaus that can I add it here

Because this repo only contains gpt models, should I add it here ?

But it will need you to be signed in to the website in your browser, basically I use cookies 😅

**Comment by oohohoo** [comment]
> can I add it here

oh yes please :)

**Comment by hlohaus** [comment]
Hello, yes you can add your provider. But it should not extend the base provider and maybe you can put it in a sub dir. It can be a good extension for the GUI. You could add it like the image gen. Thank you

**Comment by Meshwa428** [comment]
Okay will do 😊💯

**Comment by CVFA-Dev** [comment]
Hey, I think that is possible reverse this platform: 
https://platform.acedata.cloud/services/suno

**Comment by CVFA-Dev** [comment]
I had another idea, we can try to reverse the API of this mobile application called "Zone", which uses Suno and does not require authentication (for now):
https://play.google.com/store/apps/details?id=com.zona.aimusic

The problem is that you can only create one song in the free plan (actually two songs, because it generates two outputs), I can't tell if the API is open but if the app has no authentication and creates the account automatically and doesn't require any Captcha when you enter the app, I don't doubt that the API is open and any client can make requests to the API even without an account.

**Comment by CVFA-Dev** [comment]
@Meshwa428 @hlohaus

**Comment by thanhtoan1196** [comment]
any updates?
