### ISSUE TITLE
I’m really sorry. I’m still learning how to understand this usage. I’m a beginner.

### ISSUE THREAD

**Issue by lovelife0321** [xtekky/gpt4free#1756]

**Comment by norrybul** [comment]
To use the gui easily, you need to install python 3.10+ at the least. Just download the latest release and extract somewhere in your c drive. Open a command prompt in you extracted folder, create at bat file with the following scripts: 
@echo off
:: Create a virtual environment named 'venv'
python -m venv venv
:: Activate the virtual environment
call .\venv\Scripts\activate
:: Install requirements from requirements.txt
pip install -r requirements.txt
:: Run the specified Python module
python -m g4f.gui.run
Then save it as gpt4free.bat.
In command prompt type: gpt4free.bat
Wait for it to finish and run the server.
Create a bat file with this batch script:
start "" http://127.0.0.1:8080/chat/
Save it as open-client.bat
Now click open-client.bat, and wait for the browser to open the gpt4free client GUI.
It's just the simplest thing I did to make it easier for those who want to try it.
Now if you want to use the gpt4free api, you can use the first bat file, but the last script should be:
python -m g4f.api.run
This is explained in the interference api page.
Right now the api url I used was http://127.0.0.1:10000/v1 or http://127.0.0.1:10000/v1/chat/completions on any Interface to use the models at http://127.0.0.1:10000/v1/models
Try using it in ChatGPTBox Chrome addon with no api key. Just type any model on the models link and you are off to chat using gpt4free externally.
But best is try the gpt4free client ui to get used tot it.
You can try typing the scripts manually if you want to. Either way, the result is the same.
If you want to update, just replace your gpt4free folder with the new releases.
This app is supported in Win10+ only since you can't install python 3.10x there.
Please read the documentation for other details. There are many ways to run it using python as stated the gpt4free page. Mine was taken on the old threads and releases since I'm a Windows user, since I've used it last year till now. Be sure you are using Chrome browser since the cookies are needed if you logged in the free providers outside Chrome browser like Bing and the rest. It helps prolong the usage limits together with the rest. Refer to guide on using cookies if that is the case. You also read infos on [g4f at PyPi module webpage](https://pypi.org/project/g4f/) since it is related to this repository. G4f can be run the same as gpt4free, either using the scripts provided there or mine.
