### ISSUE TITLE
Help with asyncio task pending error in image generation function

### ISSUE THREAD

**Issue by noneherel** [xtekky/gpt4free#2243]
Hi everyone,

I'm encountering an issue with an image generation function that uses asyncio for asynchronous execution. Here's the relevant part of the code:
Note: i used deepinfra for this image generation
```
def generate(self, prompt: str, model: str = None, **kwargs) -> ImagesResponse:
    logging.info(f"Starting synchronous image generation for model: {model}, prompt: {prompt}")
    try:
        loop = asyncio.get_event_loop()
    except RuntimeError:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)

    try:
        result = loop.run_until_complete(self.async_generate(prompt, model, **kwargs))
        logging.info(f"Synchronous image generation completed. Result: {result}")
        return result
    except Exception as e:
        logging.error(f"Error in synchronous image generation: {str(e)}")
        raise
    finally:
        if loop.is_running():
            loop.close()
```
The function works well initially, but after a few executions, I encounter this error:

```
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-160' coro=<AsyncCurl._force_timeout() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\curl_cffi\aio.py:177> wait_for=<Future pending cb=[Task.task_wakeup()]>>
```
It seems like there's a problem with properly closing the event loop or awaiting all tasks. I would appreciate any guidance or suggestions on how to fix this issue or better manage the asynchronous tasks in this context. Specifically,
I'm wondering:

  - Should I handle the event loop differently to avoid task conflicts?
  - Is there a more efficient way to ensure all tasks are completed before the loop is closed?
  - Would switching to asyncio.run() instead of run_until_complete() be a better approach here?
  - Thanks in advance for your help!

**Comment by TheFirstNoob** [comment]
```response = await asyncio.to_thread(client.images.generate, model=service.value, prompt=prompt)```
or u can use sync_to_async (asgiref lib)

Whats i use.
Docs: https://github.com/xtekky/gpt4free?tab=readme-ov-file#image-generation

Or asyncio.run
```
import logging
import asyncio

def generate(self, prompt: str, model: str = None, **kwargs) -> ImagesResponse:
    logging.info(f"Starting synchronous image generation for model: {model}, prompt: {prompt}")
    try:
        result = asyncio.run(self.async_generate(prompt, model, **kwargs))
        logging.info(f"Synchronous image generation completed. Result: {result}")
        return result
    except Exception as e:
        logging.error(f"Error in synchronous image generation: {str(e)}")
        raise
```
There are many implementations

**Comment by kqlio67** [comment]
Hello @noneherel,

Thank you for the detailed description of your problem that you are experiencing when using asyncio for image generation. Let's take a look at your specific issues and try to provide you with a solution to resolve the "Task was destroyed but it is pending!" error.

1. **Integrating `asyncio.run()` into your existing code:**
Instead of using `run_until_complete()` inside the `generate` function, you can modify it to use `asyncio.run()` like this:

```python
def generate(self, prompt: str, model: str = None, **kwargs) -> ImagesResponse:
    logging.info(f"Starting synchronous image generation for model: {model}, prompt: {prompt}")
    try:
        result = asyncio.run(self.async_generate(prompt, model, **kwargs))
        logging.info(f"Synchronous image generation completed. Result: {result}")
        return result
    except Exception as e:
        logging.error(f"Error in synchronous image generation: {str(e)}")
        raise
```

2. **Addressing the "Task was destroyed but it is pending" error:**
This error occurs when a task is destroyed before it has completed. To avoid this, ensure that all tasks are properly awaited and completed before closing the event loop. You can use `asyncio.gather()` to wait for multiple tasks to complete.

3. **Managing the event loop and awaiting task completion:**
   - Instead of manually creating and closing the event loop, using `asyncio.run()` handles this automatically. It creates a new event loop, runs the coroutine, and closes the loop after completion.
   - To ensure all tasks are completed before the loop is closed, you can use `asyncio.gather()` to wait for multiple tasks. For example:

```python
async def generate_multiple_images(self, prompts: List[str], model: str = None, **kwargs) -> List[ImagesResponse]:
    tasks = [self.async_generate(prompt, model, **kwargs) for prompt in prompts]
    results = await asyncio.gather(*tasks)
    return results
```

4. **Switching to `asyncio.run()`:**
As mentioned earlier, using `asyncio.run()` instead of `run_until_complete()` is a better approach in your case. It handles the event loop creation and closure automatically.

**Try the following approach, which might help resolve your error:**

```python
import asyncio
from g4f.client import Client

async def main():
    client = Client()
    images = await client.async_images()
    response = await images.async_generate(
        model="flux",
        prompt="a white siamese cat",
    )
    image_url = response.data[0].url
    print(f"Generated image URL: {image_url}")

if __name__ == "__main__":
    asyncio.run(main())
```

**Here's an example of the output you might see:**

```
python main.py 
Generated image URL: https://api.airforce/imagine2?prompt=a+white+siamese+cat&size=1:1&model=flux
```

Also note that the problem may be related to the deepinfra provider itself. This provider has not been updated for some time since it started using the authorization API. It may be worth considering using alternative providers.

Try this approach, it may help to solve your problem. If it doesn't work, try another image generation provider.

Try applying these modifications to your code, and it should help resolve the "Task was destroyed but it is pending" error and improve the overall handling of asynchronous tasks in your image generation function.

**Comment by noneherel** [comment]
thank you for your help it was really helpful.
