### ISSUE TITLE
Time to repair AmigoChat

### ISSUE THREAD

**Issue by Looksh190** [xtekky/gpt4free#2289]
ERROR:root:Error 406: {"message":"not implemented","error":"Not Acceptable","statusCode":406}
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\api\__init__.py", line 160, in chat_completions
    response = await self.client.chat.completions.async_create(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\client\client.py", line 281, in async_create
    async for result in response:
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\client\client.py", line 348, in async_iter_append_model_and_provider
    async for chunk in response:
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\client\client.py", line 306, in async_iter_response
    async for chunk in response:
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\client\client.py", line 59, in to_async_iterator
    for item in iterator:
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\providers\base_provider.py", line 223, in create_completion
    yield loop.run_until_complete(await_callback(gen.__anext__))
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\nest_asyncio.py", line 98, in run_until_complete
    return f.result()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\providers\base_provider.py", line 52, in await_callback
    return await callback()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\Provider\AmigoChat.py", line 189, in create_async_generator
    raise e
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\g4f\Provider\AmigoChat.py", line 139, in create_async_generator
    raise Exception(f"Error {response.status}: {error_text}")
Exception: Error 406: {"message":"not implemented","error":"Not Acceptable","statusCode":406}
INFO:     192.168.0.118:60788 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error

**Comment by UX0l0l** [comment]
I get a similar message:

Error 403: <!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<title>Attention Required! | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />

<style>body{margin:0;padding:0}</style>



<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>



</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> amigochat.io</h2>
      </div>

      <div class="cf-section cf-highlight">
        <div class="cf-wrapper">
          <div class="cf-screenshot-container cf-screenshot-full">

              <span class="cf-no-screenshot error"></span>

          </div>
        </div>
      </div>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>

            <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>

            <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>
          </div>
        </div>
      </div>

      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">8d6ce8969e018ab0</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip">94.249.71.93</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>

  </p>
  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div>


    </div>
  </div>

  <script>
  window._cf_translation = {};


</script>

<script>(function(){function c(){var b=a.contentDocument||a.contentWindow.document;if(b){var d=b.createElement('script');d.innerHTML="window.__CF$cv$params={r:'8d6ce8969e018ab0',t:'MTcyOTYzNTk4MS4wMDAwMDA='};var a=document.createElement('script');a.nonce='';a.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js';document.getElementsByTagName('head')[0].appendChild(a);";b.getElementsByTagName('head')[0].appendChild(d)}}if(document.body){var a=document.createElement('iframe');a.height=1;a.width=1;a.style.position='absolute';a.style.top=0;a.style.left=0;a.style.border='none';a.style.visibility='hidden';document.body.appendChild(a);if('loading'!==document.readyState)c();else if(window.addEventListener)document.addEventListener('DOMContentLoaded',c);else{var e=document.onreadystatechange||function(){};document.onreadystatechange=function(b){e(b);'loading'!==document.readyState&&(document.onreadystatechange=e,c())}}}})();</script></body>
</html>

Usually happens when I try to access o1 or o1-mini. Is there a different provider I can switch to for the mean time while this issue gets fixed?
