### ISSUE TITLE
Image bug

### ISSUE THREAD

**Issue by TarKek** [xtekky/gpt4free#2296]
**Bug description**
An error occured: Blackbox: FileNotFoundError: [Errno 2] No such file or directory: './generated_images\\1729703173_53017a66-3398-4a85-bdc6-2f3e6a084f9c'

ex.
1. Go to (http://5.42.66.28:8080/chat/)
2. Click on text box
3. Write generate cat image
4. ta da

**Screenshots**
![image](https://github.com/user-attachments/assets/98f6ca21-3735-439e-85d8-76fc78ebed8c)

**Environment**
- python 3.13
- location ( ru ) ?

**Fix (from kqlio76)**

Create a folder named generated_images in the same directory where you're running g4f-gui

**Comment by kqlio67** [comment]
Hi @TarKek,

I tested and reproduced your issue. Based on the error message, it seems the script is trying to save generated images but can't find the required directory.

**Here's a simple fix:** Create a folder named `generated_images` in the same directory where you're running g4f-gui


The error occurs because the application expects this folder to exist but doesn't create it automatically. After creating the directory manually, the image generation should work properly.

**Comment by TheFirstNoob** [comment]
@kqlio67 Hi, this directory created on git and should be work correctly. Its bug.
