### ISSUE TITLE
 ERROR:root:'async for' requires an object with __aiter__ method

### ISSUE THREAD

**Issue by MH140000** [xtekky/gpt4free#2319]
when i want use api after i send a message with openai lib, i got this error in log:
 ERROR:root:'async for' requires an object with __aiter__ method, got generator  
 Traceback (most recent call last):                                              
   File "/usr/local/lib/python3.10/dist-packages/g4f/api/__init__.py", line 198, 
 in streaming                                                                    
     async for chunk in response:                                                
 TypeError: 'async for' requires an object with __aiter__ method, got generator

**Comment by MH140000** [comment]
How can fix this?

**Comment by MH140000** [comment]
thanks very much

**Comment by ahmedashraf443** [comment]
Did you manage to fix it ?

**Comment by MH140000** [comment]
@ahmedashraf443  yes you can use https://github.com/kqlio67/gpt4free

**Comment by kqvanity** [comment]
@hqnicolas 
Can either solution make a pr?

**Comment by DaVinchik** [comment]
I installed the latest version of the repository, when I try to use it through the API, I get this error:
```
Traceback (most recent call last):
  File "/app/g4f/api/__init__.py", line 198, in streaming
    async for chunk in response:
                       ^^^^^^^^
TypeError: 'async for' requires an object with __aiter__ method, got generator
```
I see that the error was fixed with previous updates, I also see that recommendations are given above, but I personally did not understand how to fix the error.
P.S. In general, I use it installed via Pip, I decided that this was the problem and installed the source, and then also tried to check it via Docker. This did not help cure the problem.
