### ISSUE TITLE
OpenaiChat: No proof_token found in .har files

### ISSUE THREAD

**Issue by phamxtien** [xtekky/gpt4free#2428]
- Ver 0.3.7.4: Provider OpenaiChat return error "No proof_token found in .har files"
- Ver 0.3.3.3 is ok

**Comment by hlohaus** [comment]
Good day. The OpenAI Chat provider requires a proof token. You can use Nodriver to generate one, or you can create one yourself. A guide for generating a .har file with a proof token is available in the readme.

**Comment by hlohaus** [comment]
@bejokun Hello,

I'm curious to know which operating system you are using. Do you have Google Chrome installed? Are you running g4f in your terminal or in a Docker container?

The error message indicates that it is unable to open or locate the browser. In a Docker container, the issue is frequently a lack of memory.

**Comment by bejokun** [comment]
> @bejokun Hello,
> 
> I'm curious to know which operating system you are using. Do you have Google Chrome installed? Are you running g4f in your terminal or in a Docker container?
> 
> The error message indicates that it is unable to open or locate the browser. In a Docker container, the issue is frequently a lack of memory.

I am using ubuntu 22.04 using normal linux terminal not using docker, and I think nodriver need open default browser profile not create new profile or other method. so we can store any cookies service using default profile
