### ISSUE TITLE
Issues with Blackbox Provider

### ISSUE THREAD

**Issue by DeveleplorAbdullahH** [xtekky/gpt4free#2433]
There are so many issues with Blackbox provider. It can't read the system prompt and gpt-4o model can not answer. Maybe, there are issues with the servers.

**Comment by Linden10** [comment]
I asked this same question and the answer is here:
https://github.com/xtekky/gpt4free/issues/2360#issuecomment-2495509264
> @Linden10 Hi, Blackbox is sometimes overloaded and because of this the dialogue, instructions or system settings are lost. For this provider such data losses are quite normal already. That's why I didn't add this provider to the bug list.

I tested this manually with Blackbox in g4f gui, sending messages one at a time and testing the system prompt and found out that Blackbox randomly breaks, ignoring the system prompt and such after responding due to the reasons above.

Yup! Nothing that can be done about it sadly...

**Comment by DeveleplorAbdullahH** [comment]
And there is an issue with Copilot Provider. I wrote a long system prompt to Copilot provider and when I ask something to Copilot provider it says: "RuntimeError: Error: {'event': 'error', 'id': '0', 'errorCode': 'text-too-long'}"
