### ISSUE TITLE
takedown discussion

### ISSUE THREAD

**Issue by Emasoft** [xtekky/gpt4free#247]
Who care about the takedown? Just create a Docker image ready to be hosted anywhere.
Just create a Docker image and add a button to host it automatically on some free service, like those listed here:  https://stackdiary.com/free-hosting-for-developers/

For example add a "Deploy on Railway" button:
https://docs.railway.app/deploy/deploy-on-railway-button

![IMG_5931](https://user-images.githubusercontent.com/713559/235137123-537d0951-b1db-4e4d-b24e-e196364e8bf2.jpeg)

Render also provides a "Deploy To Render" button [https://render.com/docs/deploy-to-render](https://render.com/docs/deploy-to-render)

**Comment by xtekky** [comment]
wym by that ?

**Comment by Emasoft** [comment]
> wym by that ?

Any user can deploy his own docker service clicking on the "Deploy on Railway". Hundreds of mirrors of the freegpt server, no one can take all down.

**Comment by 9fo** [comment]
we can't just do that, we don't want to get sued by the companies. let's just respect their wishes alright?

**Comment by Emasoft** [comment]
> we can't just do that, we don't want to get sued by the companies. let's just respect their wishes alright?

You are not getting sued. At best Railway or Render will receive a takedown notice and will stop the hosting of a certain user. But a new user will redeploy the docker again later, and the service will be online again. There will be hundreds of deployments, they cannot take down all at once.

**Comment by 9fo** [comment]
> > we can't just do that, we don't want to get sued by the companies. let's just respect their wishes alright?
> 
> You are not getting sued. At best Railway or Render will receive a takedown notice and they will comply stopping the hosting of a certain user. But a new user will redeploy the docker again later, and the service will be online again. There will be hundreds of deployments, they cannot take down all at once.

we actually are, OpenAI has already sent a DMCA strike via a legal team. not through GitHub we cant disclose the exact information in the letter due to legal reasons but along the lines if we continue doing this. yes we will get sued

**Comment by xtekky** [comment]
There is a big difference between getting a threatening takedown request from openai's legal team and just a little dcma from GitHub. This project is also way too famous now.

**Comment by Emasoft** [comment]
> > > we can't just do that, we don't want to get sued by the companies. let's just respect their wishes alright?
> > 
> > 
> > You are not getting sued. At best Railway or Render will receive a takedown notice and they will comply stopping the hosting of a certain user. But a new user will redeploy the docker again later, and the service will be online again. There will be hundreds of deployments, they cannot take down all at once.
> 
> we actually are, OpenAI has already sent a DMCA strike via a legal team. not through GitHub we cant disclose the exact information in the letter due to legal reasons but along the lines if we continue doing this. yes we will get sued

I seriously doubt that such legal action will won. You are not doing anything different from what a Chrome extension does. The service is still the one provided by the original website. You are just improving the UI.

**Comment by xtekky** [comment]
yeah, I am investigating it, need to be careful though, we'll see in the future

**Comment by valicsek** [comment]
So the company that made copilot the one that is talking about legal problems? 

https://www.infoq.com/news/2022/11/lawsuit-github-copilot/

**Comment by xtekky** [comment]
no, its openai  itsself @valicsek, well at least it appears to be.

**Comment by vaibhavard** [comment]
How is it related to openai? , when we are not directly exploiting its services but instead other companies that offer access? These companies are paying right?

**Comment by NSbuilder** [comment]
The hosting is not the problem. The problem is the api thing might get fixed by openai or stop working

**Comment by LukeSaward1** [comment]
> I seriously doubt that such legal action will succeed.

You have no idea about how lawsuits work. If the courts find GPT4Free in breach of OpenAI's IP/copyright, the ruling will be in OpenAI's favour.

**Comment by saulojoab** [comment]
well, seems like i'll need to keep my local cloned repository a secret then.

**Comment by kevnoutsawo** [comment]
Hello all,
I discovered this project yesterday and if I understand the functioning well, it uses compromised third-party OpenAI API keys to access GPT models free of charge. I assume it would mean that the owners of the compromised keys will end up with huge bills at the end of the month. So technically it is not "free", it is just paid for by someone else. If those third parties are not happy to pay, then retaliations of all sorts are just a matter of time. OpenAI will also step in as multiple compromised keys might be seen by the public as a security failure from them.

**Comment by xtekky** [comment]
there is NO COMPROMISED KEYS, just using public apis, means instead of having a site interface u directly use connection to the server

**Comment by xtekky** [comment]
and what I don't understand, there is other repositories directly using openai like Chatgpt by archeong08 which is still up and way more famous

**Comment by Emasoft** [comment]
> > I seriously doubt that such legal action will succeed.
> 
> You have no idea about how lawsuits work. If the courts find GPT4Free in breach of OpenAI's IP/copyright, the ruling will be in OpenAI's favor.

I know one thing or two about lawsuits. Not all copyright claims or usage licenses are constitutional or legal. Just because you accepted a license that imposes a restriction on the usage, that does not mean that such restriction was legal or valid in the first place. Believe me: you cannot restrict the use of the output you get from a service. Once you get the output response from those websites in a perfectly legal way (and freeGPT does not use any illegal or stolen key), you can do whatever you want with that output. It was generated from your input, after all. It is protected by the law since it is something you own and that contain private and personal data. Once those bytes leave the original server, they cannot tamper with them or claim any right on them. Using a Python script instead of a browser is just a technicality that doesn’t change this fundamental fact.
OpenAI, on the other hand, has still to answer for taking our code and use it to train GPT without our consent. That is illegal. And they now want to restrict our right to use GPT? How ironic...

**Comment by gabereiser** [comment]
@Emasoft that's for the courts to decide should it get there, you can't just assume you're in the right because you don't believe the TOS was legal. If the takedown is due to "circumventing" then no docker container will ever make it legal. The war between public code and GPT and OpenAI isn't going to be here on github.

**Comment by Emasoft** [comment]
You need to wake up. The world is not a good place. If you don’t fight for your rights, they are going to take them from you.

**Comment by xtekky** [comment]
I got a dcma before, and it was because I leaked full security protected code of TikTok, not because I did a script using 3d party websites with bots, all this is quite weird and there is surely a wrong public image of gpt4free, it’s just automating sites and has itself not any content belonging to openai

**Comment by JakoDel** [comment]
> and what I don't understand, there is other repositories directly using openai like Chatgpt by archeong08 which is still up and way more famous

lol the project got archived today, nice.
anyways, I too have found out about this only now (damn me) but come on man something like this was bound to happen, especially after creating a whole discord server for the project. people don't use logic, or better yet, they form their opinion about stuff they don't understand all the time. would have been a cool project to share on some more obscure platform, this way it would have taken more time for people to start spamming it everywhere :)
but still gl with your project guys

**Comment by kevnoutsawo** [comment]
acheong08 has just archived his project. I don't know if it is related or not.
There are solutions that allow one to use GPT-3.5 by abstracting away the UI but still using one's ChatGPT account. On OpenAI's, side, that probably appears as the user making normal prompts from the default UI.
The big issue with using public APIs, even when they are advertised as free is that it defeats their purpose and thus makes the investment worthless for them. OpenAI models are not free, nor is the computing power they use for inference. Whenever you see any of them used anywhere, someone had to pay and they did it because they had interests. For instance, Bing includes access to GPT-4 (with 2000 characters limit) for "free" while ChatGPT Plus users pay to access the same model. The same goes for Dall-e which can also be used for "free" via Bing while regular access is paid. Their goal is to become a dominant search engine and defeat Google. They also want Edge to surpass Chrome in browser market shares. They know that if they achieve that, they will have at least hundred of billions of new revenue. That is why they are willing to invest billions in research and daily upkeep of these models. ChatGPT was a way for them to get massive user feedback and real-life human conversations to improve their models, that is why it was given to the public for "free" and also why they still have a free tier. All other services that give access to GPT-4 do so in order to increase their user base and further their bottom line.
When you create indirect access to their service, you destroy their business model as they support those APIs but will not get the expected return.

I think the case of a restaurant might be a befitting analogy. A restaurant is a public place, you can come in to meet people and talk with them. You can order water which is free, sit on their chairs and use their space. However, if you don't order anything else, they don't make money off of you. If most people come in, do that, and leave, they won't be able to support their staff, pay their rent and keep the place clean and welcoming. That is why waiters will keep prompting you to order something, and if they find out that you have no intention to order anything paid, they might even kick you out and you can't rightfully blame them just because it is a public place.
Likewise, when the companies who own those apis find out about this project, I envision them having the same reaction: "Let's shut that down A.S.A.P.".

At least, that is my understanding of the situation. Also, I remember the case of Faker.js from last year that showed us clearly that we don't actually own any of the code we upload to GitHub, no matter which License terms are in a repository. Of course, Marak did not handle things ethically but what GitHub did set a clear precedent. If they don't like the way a repository is handled, they can simply take it and do as they please, they can even exclude you from a project you started and worked on for years. Considering that Microsoft owns GitHub and OpenAI, I won't be surprised to come back tomorrow and see that this repository has just disappeared without explanations given to you or anyone else.

**Comment by xtekky** [comment]
@kevnoutsawo I understand this better now. They are scared all sites used here shut down, and they loose their sources of income ...?

**Comment by AbdelrhmanNile** [comment]
@xtekky openai will NEVER be able to stop this, evenif this repo got taken down THOUSANDS other repos will appear

**Comment by AbdelrhmanNile** [comment]
@xtekky if you are concerned with dmca or whatever, find someone outside of usa to continue maintaining it

**Comment by HirCoir** [comment]
> @xtekky if you are concerned with dmca or whatever, find someone outside of usa to continue maintaining it

Instead, you can try bringing open source projects, like OpenAssistant, Llama.cpp, Alpaca.cpp. Projects that are at the GPT level, for example the Vicuna-ggml-13b model which is just as powerful as GPT4.
You can create projects with interfaces and publish them in your repo, you can look for free services to run them like colab, deepnote.com, huggingface.co (Currently this allows you to create a space to deploy your APP, allocating 2CPU, 16GB of ram completely free)
You can create or package models on huggingface.co, create apis and publish them in your repo, in such a way that users have access to a bot, just an idea... Currently there are AI models that are at the GPT level, I have tried OpenAssistant-ggml and it has worked excellent for me on a Linux instance

**Comment by kevnoutsawo** [comment]
> @kevnoutsawo I understand this better now. They are scared all sites used here shut down, and they loose their sources of income ...?

At the moment, it is an arms race to AGI. Most companies in the AI niche are not profitable yet. Their main short-term goal is to grow their market share in whatever they do and grow their user base. Investors are putting in billions so there is cash flow so revenue is not their major concern at the moment. They are trying to secure a first-mover advantage and get ahead of the competition. Offering free access to AI models is part of their strategy to attract users. They want people to form habits and have their services feel so necessary that whenever they start a subscription, people open their wallets without asking questions. Thus, they want people to come to the same apps, over and over again. Lots of people now use Bing just because of GPT-4 access but a few months ago, Bing was a joke. The same goes for Duolingo which was a meme among language learners but now many will download that app just to talk with Max (their GPT-4 powered bot). ChatGPT had the fastest growth of the digital era. Those companies are trying to piggyback on the current buzz to lift themselves to the moon. For this strategy to keep working, they need GPT-4 to stay an exclusive premium experience that you will either pay for or feel a moral debt to whichever app or company gives you access to it free of charge.

Those companies are a revenue stream for OpenAI so it is in their interest to see them grow. They don't want GPT-4 to become too easy to access because scarcity increases value.

**Comment by givensuman** [comment]
Y'all let's maybe not bully the owner of this repo unless we're willing to pay their legal fees. It's great that we're all into FOSS but there's idealism and there's reality.

**Comment by xtekky** [comment]
@AbdelrhmanNile I am not based in the USA, forgot to mention that the legal team did not notify GitHub and send the request to some random email I checked out of pure luck I left somewhere on my GitHub profile

**Comment by xtekky** [comment]
Overall this looks a bit shady and solely based on this repo's popularity

**Comment by python-nerd-3** [comment]
> You need to wake up. The world is not a good place. If you don’t fight for your rights, they are going to take them from you.

oh i'm sorry you can't steal code and redistribute it for free!!! i can totally understand why you are being existential about it!!!

**Comment by LukeSaward1** [comment]
@python-nerd-3 Stop trolling, you annoying individual. I wouldn't be surprised if everyone around you casts you aside due to how much of an annoying person you are.

**Comment by arch-btw** [comment]
![gpt4free](https://user-images.githubusercontent.com/57669023/235278381-51048cda-4484-4ed8-a50d-d6612dc54194.png)

**Comment by acheong08** [comment]
> acheong08 has just archived his project. I don't know if it is related or not.

No. That's due to burnout

**Comment by acheong08** [comment]
> and what I don't understand, there is other repositories directly using openai like Chatgpt by archeong08 which is still up and way more famous

https://github.com/acheong08/ChatGPT/issues/394

**Comment by acheong08** [comment]
> Overall this looks a bit shady and solely based on this repo's popularity

That is the most likely case. I never achieved the same level of fame (in the form of articles/posts on social media) and my traffic comes from developers, not the general public.

There is one concern with your work is https://github.com/xtekky/chatgpt-clone. Because you are hosting it yourself rather than simply providing source code, you become personally liable for people's usage, which according to laws in some countries (apparently the UK), makes you monetarily liable for damages. (Disclaimer: I have no idea how law works. I just asked ChatGPT & Bard & Bing)

**Comment by acheong08** [comment]
> one of my contacts at openai told me that his project crossed a line for them. i wouldn't expect this ends well for him since from what I understand, his project is piggybacking off of other people's accounts, and a lot of those people can't afford to pay their bills

- Someone with contact with OpenAI staff (not me)

**Comment by acheong08** [comment]
> Those companies are a revenue stream for OpenAI so it is in their interest to see them grow. They don't want GPT-4 to become too easy to access because scarcity increases value.

No. OpenAI profits either way since the smaller creators are paying for it. This repo doesn't make access free, it just makes it so other people pay

**Comment by bfinan** [comment]
if you live by Micro$oft you'll die by Micro$oft

the only solution is anonymous free software jihad

**Comment by evanrich** [comment]
This guy doesn't get docker containers.  Docker containers aren't any good if the code inside them never gets updated.   If the project has to get taken down, no new docker containers.  If the creator gets sued into oblivion, no new code for a new docker container. Yes, you can host it on dockerhub/github/google/etc, but someone would still need to continue updating code for new images.
