### ISSUE TITLE
Runtime warning - could't find ffmpeg or avconv

### ISSUE THREAD

**Issue by RookyCoder** [xtekky/gpt4free#342]
![image](https://user-images.githubusercontent.com/129950420/235457676-56b6f627-0457-45ff-b0ba-b3be4bbaed0b.png)
is it a minor issue but not affecting usage? Due to virtual env? 
=================

@xtekky good work.

Any chances to choose which model/sites priority? It seems not support continuous understanding previous message?
virtual env, python 3.11 ,window 11

- git clone

- pip install requirements.txt

- Move streamlit_app.py from ./gui to the base folder

- then run:
python -m streamlit run streamlit_app.py

**Comment by spacewalkingninja** [comment]
just sudo apt-get install ffmpeg. I wonder what they are using ffmpeg for tho. 
@xtekky , or anybody who knows the code better, mind to explain?

**Comment by EasternPA** [comment]
I'm trying to get the docker version going, so I added 'fffmeg' after 'git' on the 'apt install' command in Dockerfile. That cleared that error for me.

**Comment by LDT-dream** [comment]
@RookyCoder I also met this error in the window environment and solved it in this way.
1. Download the FFmpeg from the webpage instead of using pip, you can download it following [ this guide](https://www.wikihow.com/Install-FFmpeg-on-Windows).
2. Restart the computer(My environment needs to restart)
3.  open the Command Prompt or PowerShell and run:
```
ffmpeg
```
To confirm the `ffmpeg` is installed correctly, and not see the `could't find ffmpeg or avconv` in this project.
(But I meet another error `[OSError(9, 'The handle is invalid.', None, 6)](https://stackoverflow.com/questions/69747151/python-serial-clearcommerror-failed-oserror9-the-handle-is-invalid-none)`)

**Comment by tilefishpoele** [comment]
it doesn't seem to affect usage though. can anyone confirm what its used for?

**Comment by MIDORIBIN** [comment]
I'm getting an error with pydub, it seems quora depends on that library.

quora -> pypasser -> pybub

If you don't use quora, you can ignore this warning.
