### ISSUE TITLE
https://chat.g4f.ai/chat redirects to https://www.profitabledisplaynetwork.com

### ISSUE THREAD

**Issue by rpbp58** [xtekky/gpt4free#356]
When I click on your website, my browser tries to go to https://www.profitabledisplaynetwork.com, a known malicious website.

Can you explain?

**Comment by baigeiapi** [comment]
maybe you just click on the ad on that time?

**Comment by rpbp58** [comment]
There were no ads.  It comes up as soon as you click the link.

**Comment by baigeiapi** [comment]
idk,it didnt happen on me,it still fine when i open chat.g4f.ai

**Comment by xtekky** [comment]
This is an issue with the ads provider, i am investigating it, please join the discord server in the meantime

**Comment by marek22k** [comment]
Maybe use something like uBlock origin or NoScript?

**Comment by mitchcapper** [comment]
yeah its confusing.  If you are on desktop you have to blacklist profitabledisplaynetwork-com to visit.  Its known to be an aggressive adware/malware distributor: https://securedstatus.com/remove-profitabledisplaynetwork-com/  but as it is literally sent down in the root /chat/ page it is clearly intentional.
