### ISSUE TITLE
failed to do request

### ISSUE THREAD

**Issue by YJ-KER** [xtekky/gpt4free#420]
An error occurred: failed to do request: Get "https://you.com/api/streamingSearch?q=%E9%B8%A1%E5%85%94%E5%90%8C%E7%AC%BC%EF%BC%8C%E5%85%B1%E6%9C%8930%E4%B8%AA%E5%A4%B4%EF%BC%8C88%E5%8F%AA%E8%84%9A%E3%80%82%E6%B1%82%E7%AC%BC%E4%B8%AD%E9%B8%A1%E5%85%94%E5%90%84%E6%9C%89%E5%A4%9A%E5%B0%91%E5%8F%AA%EF%BC%9F&page=1&count=10&safeSearch=Moderate&onShoppingPage=False&mkt=&responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&domain=youchat&queryTraceId=8e2db342-1d7d-4bb4-aa97-46b83d5c3c0b&chat=%5B%5D": dial tcp 45.114.11.238:443: i/o timeout (Client.Timeout exceeded while awaiting headers). Please make sure you are using a valid cloudflare clearance token and user agent.

**Comment by wangerbin** [comment]
I have similar issues here :An error occurred: failed to do request: Get "https://you.com/api/streamingSearch?q=%E7%8E%B0%E5%9C%A8%E7%9A%84%E6%97%B6%E9%97%B4&page=1&count=10&safeSearch=Moderate&onShoppingPage=False&mkt=&responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&domain=youchat&queryTraceId=c7246749-0b28-45ff-9332-b9d4e4415317&chat=%5B%5D": dial tcp 103.56.16.112:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.. Please make sure you are using a valid cloudflare clearance token and user agent.

**Comment by wangerbin** [comment]
我发现是我的服务没有走代理程序，这个服务要在哪里设置，网络请求走代理程序？
I found out that my service did not use a proxy program. Where should I set up this service and use a proxy program for network requests?

**Comment by ly40** [comment]
> 我发现是我的服务没有走代理程序，这个服务要在哪里设置，网络请求走代理程序？ I found out that my service did not use a proxy program. Where should I set up this service and use a proxy program for network requests?

export https_proxy=http://127.0.0.1:7890
