### ISSUE TITLE
An error occurred: failed to do request

### ISSUE THREAD

**Issue by Dufren8820** [xtekky/gpt4free#444]
An error occurred: failed to do request: Get "https://you.com/api/streamingSearch?q=%E5%87%A0%E7%82%B9%E4%BA%86%EF%BC%9F&page=1&count=10&safeSearch=Moderate&onShoppingPage=False&mkt=&responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&domain=youchat&queryTraceId=f8e894f4-faa7-4ad2-b894-4b95f0ef2c03&chat=%5B%5D": dial tcp 127.0.0.1:10809: connectex: No connection could be made because the target machine actively refused it.. Please make sure you are using a valid cloudflare clearance token and user agent.

how to fix this problem?please!

**Comment by williammyq** [comment]
set your proxy

**Comment by WGXT** [comment]
the same. Have you solved it now？

**Comment by williammyq** [comment]
您好,您的邮件我已经收到,谢谢您,辛苦了

**Comment by paradoxgoo** [comment]
請問該怎麽設置proxy

**Comment by WGXT** [comment]
> set your proxy

Can you go into more detail?

**Comment by paradoxgoo** [comment]
An error occurred: failed to do request: Get "https://you.com/api/streamingSearch?q=nihao+&page=1&count=10&safeSearch=Moderate&onShoppingPage=False&mkt=&responseFilter=WebPages%2CTranslations%2CTimeZone%2CComputation%2CRelatedSearches&domain=youchat&queryTraceId=d984796b-3d15-4c3c-b546-7d4e64d535cf&chat=%5B%5D": dial tcp 127.0.0.1:10808: connectex: No connection could be made because the target machine actively refused it.. Please make sure you are using a valid cloudflare clearance token and user agent.

how to fix this problem?please!

**Comment by laulguo** [comment]
https://github.com/xtekky/gpt4free/issues/381#/
can solve the problem
