### ISSUE TITLE
Forefront Takedown Request

### ISSUE THREAD

**Issue by JimmyGreaser** [xtekky/gpt4free#460]
Hey Tekky, my name is Jimmy Greaser (https://www.linkedin.com/in/jimmygreaser/) and I'm a cofounder at Forefront (chat.forefront.ai). We think what you're doing with GPT4Free is very cool, but we're going to have to ask again that you remove Forefront. We're a team of 3 providing a free service at quite a large expense so we'd appreciate if you'd prevent this from happening.

**Comment by spacewalkingninja** [comment]
I am very much against this! We need access to GPT4. Do you know I am in waiting queue for GPT4 and STILL CAN NOT USE IT EVEN IF I WANT TO PAY FOR IT?
Very bad, anti democratic, anti consumer, anti evolution, anti everything good in humanity!

**Comment by Delamcode** [comment]
That is OpenAI’s fault, not forefront’s. I think forefront is a great project, and I was a little sad when I saw it would be added to this service, as I knew that limits would have to be put in place for forefront (5m/3h) sooner rather than later. Both projects are great however and I hope they can keep improving!
