### ISSUE TITLE
ImportError: cannot import name 'PasswordGenerator' from 'password_generator' 

### ISSUE THREAD

**Issue by Ir3kt4fun** [xtekky/gpt4free#645]
ImportError: cannot import name 'PasswordGenerator' from 'password_generator' (C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\password_generator\__init__.py)

Traceback:
File "C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
File "C:\Users\Acer\Desktop\gpt4free-main\gui\streamlit_chat_app.py", line 10, in <module>
    from query_methods import query, avail_query_methods
File "C:\Users\Acer\Desktop\gpt4free-main\gui\query_methods.py", line 7, in <module>
    from gpt4free import quora, forefront, theb, you
File "C:\Users\Acer\Desktop\gpt4free-main\gui\..\gpt4free\__init__.py", line 6, in <module>
    from gpt4free import usesless
File "C:\Users\Acer\Desktop\gpt4free-main\gui\..\gpt4free\usesless\__init__.py", line 8, in <module>
    from password_generator import PasswordGenerator

ex.
installed password generator and random password generator and every module before them
streamlit run gui/streamlit_chat_app.py
Error appears

I've no idea why the password_generator.py ends up in site-package without it's own folder, but it gives me this error regardless of where it's placed

**Screenshots**
![bandicam 2023-06-05 16-18-13-281](https://github.com/xtekky/gpt4free/assets/135593526/89e9a71a-eac7-41e3-a854-8d99b03fdee0)
![bandicam 2023-06-05 16-18-57-701](https://github.com/xtekky/gpt4free/assets/135593526/7e2700a5-4258-4a5a-b123-c387f0d1f9a5)
![bandicam 2023-06-05 16-19-04-506](https://github.com/xtekky/gpt4free/assets/135593526/5add6907-ad9a-4b72-a76a-e9ecbc805a2c)

**Comment by LopeKinz** [comment]
the module "password_generator.py" is not a part of this project.

**Comment by MisterEMachine** [comment]
I am getting this same error message

**Comment by TranquilTonic** [comment]
It seems that the error is caused by the import statement `from password_generator import PasswordGenerator` in the file `gpt4free/usesless/__init__.py`. The error message indicates that Python cannot find the `PasswordGenerator` module in the `password_generator` package.

To fix this error, you can try changing the import statement to `from password_generator.password_generator import PasswordGenerator`. This should import the `PasswordGenerator` class from the `password_generator` package correctly.

Additionally, make sure that the `password_generator` package is installed in your Python environment. You can install it using `pip install password_generator`.

If you still encounter issues after trying the above steps, please let me know and provide any updated error messages or code snippets.

**Comment by lysanne4774** [comment]
can u please explain how you solved it
