### ISSUE TITLE
Instruction imporper

### ISSUE THREAD

**Issue by COALROCK8642** [xtekky/gpt4free#675]
Dude, the steps from making test.py is not working. Or I don't know how to setup.

**Comment by xtekky** [comment]
Where are you stuck, the instructions should be pretty straightforward

**Comment by eastsunda** [comment]
He's right bro, I'm not sure if it's intentional or not. If it is I understand, but I also got lost with your instructions, they kind of just stop at import gf4, and anyways in my case I'm getting g4f module not found error when trying to run app.py. I'm not even sure if that's what I'm supposed to do but I tried that anyway?

**Comment by Calmwaters77** [comment]
i had the same error and then i double checked the problem and the error is in your own message explained. You, as did I, tried to import gf4 but you want to import g4f as the error-message and the instructions from the github repo shows. 
As a sidenote, always be polite to the creator of a github repository, especially if its done for free.
