### ISSUE TITLE
How can I set cookies for Bard Provider?

### ISSUE THREAD

**Issue by eienmojiki206** [xtekky/gpt4free#774]

**Comment by bagusindrayana** [comment]
just add args/param auth="random_string" when call `ChatCompletion.create`, 
```python
response = ChatCompletion.create(model=Model.palm, 
                                     stream=streaming,
                                     messages=messages,
                                     provider=Provider.Bard,
                                     auth="random_cookie")
```

actually we dont need cookie anymore because Provider.Bard already handle cookie problem https://github.com/xtekky/gpt4free/blob/a8f24951427bbc6115649e039c059707327f8b57/g4f/Provider/Providers/Bard.py#L12C3-L12C3

but because Provider.Bard mark needs_auth as True https://github.com/xtekky/gpt4free/blob/a8f24951427bbc6115649e039c059707327f8b57/g4f/Provider/Providers/Bard.py#L7
we need set auth args or we will get error https://github.com/xtekky/gpt4free/blob/a8f24951427bbc6115649e039c059707327f8b57/g4f/__init__.py#L14

**Comment by Akio1210** [comment]
> just add args/param auth="random_string" when call `ChatCompletion.create`,
> 
> ```python
> response = ChatCompletion.create(model=Model.palm, 
>                                      stream=streaming,
>                                      messages=messages,
>                                      provider=Provider.Bard,
>                                      auth="random_cookie")
> ```
> 
> actually we dont need cookie anymore because Provider.Bard already handle cookie problem
> 
> https://github.com/xtekky/gpt4free/blob/a8f24951427bbc6115649e039c059707327f8b57/g4f/Provider/Providers/Bard.py#L12
> 
> but because Provider.Bard mark needs_auth as True
> 
> https://github.com/xtekky/gpt4free/blob/a8f24951427bbc6115649e039c059707327f8b57/g4f/Provider/Providers/Bard.py#L7
> 
> 
> we need set auth args or we will get error
> https://github.com/xtekky/gpt4free/blob/a8f24951427bbc6115649e039c059707327f8b57/g4f/__init__.py#L14

I follow that and get KeyError: "DBUS_SESSION_BUS_ADDRESS"

**Comment by bfilipov** [comment]
```   
    result = g4f.ChatCompletion.create(model=model,
                                       provider=provider,
                                       stream=streaming,
                                       auth="random_cookie",
                                       messages=[{"role": "user", "content": f"{query}"}], )
```

ValueError: g4f.Provider.Providers.Bard does not support 'stream' argument

**Comment by OlegRuban-ai** [comment]
Does anyone have a solution to the problem? I am getting this same error: DBUS_SESSION_BUS_ADDRESS

**Comment by johnd0e** [comment]
@OlegRuban-ai 
Try to update.

**Comment by pandawatools** [comment]
Does anyone have a solution to the problem? I am getting this same error: DBUS_SESSION_BUS_ADDRESS
