### ISSUE TITLE
Is it really gpt-4 model in ora module?

### ISSUE THREAD

**Issue by mbogomazov** [xtekky/gpt4free#87]
Why are you sure it is really 'gpt-4'? Because I asked a model about it and this is what it says about it: 

`Currently, I am using **GPT-3** to provide assistance and information. GPT-4 has not been released yet. If you have any questions, feel free to ask, and I'll do my best to help you.`.
I used gpt4 ora model not so long (and maybe it is a problem, I should practice in prompt engineering) but in my opinion its answers is worse than Open AI gpt-4 (i used it too), can you prove that is really gpt-4 and not gpt-3?

**Comment by xtekky** [comment]
Hi, it passed the tests i submitted it and has worse performance compared to other models, also, it is prompted in the background so that may degrade performance and gpt-4 will generally say that it does not know about gpt4.

asking gpt-4 who it is
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/98614666/233856460-4db80eb9-636f-430d-9047-9a5468e8a56f.png">

gpt-3.5 in ora.sh
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/98614666/233856524-a38217c0-471d-4f20-8782-abcd82fc3ec2.png">

gpt-4 in ora.sh
<img width="833" alt="image" src="https://user-images.githubusercontent.com/98614666/233856553-ade7261b-e0b8-4746-bd5d-94efc6884a8d.png">

**Comment by DanielShemesh** [comment]
It is, ask it "Summarize [RANDOM_TOPIC], with each word starting in the next letter in the alphabet". This is a prompt that GPT-3.5-turbo fails at.

**Comment by xmoufyy** [comment]
how do i even run the python script

**Comment by xtekky** [comment]
@xmoufyy, if you are not familiar with python, you may refer to an online tutorial or ask chatgpt, to use the python script simply move it from `/testing` into to base folder and then run it (`python3 filename.py`

**Comment by xmoufyy** [comment]
![image](https://user-images.githubusercontent.com/128886647/233870420-9e7f64ab-cb8a-4885-a67b-b606654e98f7.png)

**Comment by xmoufyy** [comment]
> ![image](https://user-images.githubusercontent.com/128886647/233870420-9e7f64ab-cb8a-4885-a67b-b606654e98f7.png)

this is what happens when i tried to do what you said

**Comment by xmoufyy** [comment]
fixed it

**Comment by taiyi747** [comment]
Right, it is a GPT-4 disguised as GPT-3.5.
GPT-4 is still too expensive at the moment.

**Comment by xtekky** [comment]
@taiyi747 no, it is gpt-4 lol, this is the whole point of the discussion
