### ISSUE TITLE
Error installing aiohttp

### ISSUE THREAD

**Issue by egergeorge** [xtekky/gpt4free#980]
**error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]**

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aiohttp
  Building wheel for frozenlist (pyproject.toml) ... done
  Created wheel for frozenlist: filename=frozenlist-1.4.0-cp312-cp312-win_amd64.whl size=44764 sha256=d91b35d89e012ae6702f919c3bea809269c45a32825daad8f9e11f87265adaaa
  Stored in directory: c:\users\egerg\appdata\local\pip\cache\wheels\f1\9c\94\9386cb0ea511a93226456388d41d35f1c24ba15a62ffd7b1ef
  Building wheel for multidict (pyproject.toml) ... done
  Created wheel for multidict: filename=multidict-6.0.4-cp312-cp312-win_amd64.whl size=28151 sha256=caf7fb64af0b50ab990f75b023add1fad45ef145726c63f68a8e129fab06a4ba
  Stored in directory: c:\users\egerg\appdata\local\pip\cache\wheels\f6\d8\ff\3c14a64b8f2ab1aa94ba2888f5a988be6ab446ec5c8d1a82da
  Building wheel for yarl (pyproject.toml) ... done
  Created wheel for yarl: filename=yarl-1.9.2-cp312-cp312-win_amd64.whl size=58830 sha256=0bc08126b728ae13b4e5f8a7c14a7e6a551dbddf16cb86efc93c6cf0ee01d287
  Stored in directory: c:\users\egerg\appdata\local\pip\cache\wheels\84\e3\6a\7d0fa1abee8e4aa39922b5bd54689b4b5e4269b2821f482a32
  Building wheel for lz4 (pyproject.toml) ... done
  Created wheel for lz4: filename=lz4-4.3.2-cp312-cp312-win_amd64.whl size=98143 sha256=16e3ce322dafde7c51519e180a41d422d1aacd59513b02f487e40c5e8f7f2189
  Stored in directory: c:\users\egerg\appdata\local\pip\cache\wheels\88\a9\e4\0235fcc955a52236bc67fdb6a43fc36171f48b3ccf6a67aebd
Successfully built frozenlist multidict yarl lz4
**Failed to build aiohttp
ERROR: Could not build wheels for aiohttp, which is required to install pyproject.toml-based projects**

**Comment by xtekky** [comment]
This is a problem with the `aiohttp` python package and not gpt4free itsself.

**gpt-4 debug**:
This error message is saying that there was an issue when trying to compile the aiohttp Python package from source.

Here are a few possible solutions:

1. Upgrade setuptools, wheel, and pip:
   
   `pip install --upgrade setuptools wheel pip`

2. If you're trying to install a specific version of aiohttp, try installing the latest version instead. Sometimes, compilation issues are fixed in newer releases.

3. You might need to install Microsoft Visual C++ Compiler, which is required for building certain Python packages. You can do this from the official Microsoft website.

4. Try to install the compiled version of the package for your platform. For example, if you're on Windows, you might be able to install the wheel file for aiohttp directly, without having to compile it from source.

5. If all else fails, you could try using a Python distribution such as Anaconda, which often come with pre-compiled packages and can help avoid issues such as these.

**Comment by 6562680** [comment]
Fixed via downgrade python to 3.9

**Comment by nitsik** [comment]
`pip3 install --upgrade setuptools wheel pip`
helped me for debian 10
